config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'

  devise_for :admins
  devise_for :users, controllers: { registrations: 'users/registrations', confirmations: 'confirmations' }

  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
	end

  resources :users do

  	resource :profile
  	resources :employments do
      resources :leave_requests do
        resource :rejection_message
      end
      get 'leave_request_by_hr' => 'leave_requests#leave_request_by_hr'
      resources :add_leaves, only: [:new, :create]
    end
  end

  resources :companies do
    resources :leave_types
    resources :holidays
    resources :departments
    resources :costs
    resources :reports, only: [:index] do
      collection do
        get :remaining_leaves
      end
    end
    resources :projects do
      get 'enter_time', on: :collection
      post 'entered_time', on: :collection
      get 'reports', on: :collection
      post 'create_client', on: :collection
    end
    resources :time_requests do
      get 'excel_export', on: :collection
    end
    resources :project_times, only: [:update, :create]
    get 'employees' => 'companies#employees_index'
    get 'leave_requests' => 'companies#leave_requests_index'
    resources :invites
  get 'import_page' => 'companies#import_page'
    get 'employee_import_page' => 'companies#employee_import_page'
    post :import_employees
    post :delete_employees
    post :import_leave_requests
    post :delete_leave_requests
  end

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications/notification_index' => 'notifications#notification_index'
  get 'notifications/read_all', to: 'notifications#read_all'


  namespace :dashboard do
    resources :contact_messages
    resources :endorsements
    resources :features
    resources :owners
    resources :plans
    resources :roles
    resources :testimonials
    resources :site_settings
    resources :landing_page_settings
    resources :user_home_page_settings
    resources :plans
    root to: "site_settings#index"
    devise_for :admins, skip: :registrations
  end

  get 'search' => 'pages#search'
  get 'team' => 'pages#team'
	get 'about' => 'pages#about'
	root 'pages#home'
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ActionController::Base

  protect_from_forgery
  protected
  http_basic_authenticate_with name: "admin", password: "!tseklisadministrator65fb35f526"
end

app/controllers/dashboard/contact_messages_controller.rb
class Dashboard::ContactMessagesController < Dashboard::ResourceController
end

app/controllers/dashboard/endorsements_controller.rb
class Dashboard::EndorsementsController < Dashboard::ResourceController

  def endorsement_params
  	params.require(:endorsement).permit(
            :id,
            :name,
            :photo,
            :link,
            :award_name,
            :rating,
            :description,
            :active
            )
  end
end

app/controllers/dashboard/features_controller.rb
class Dashboard::FeaturesController < Dashboard::ResourceController
  def feature_params
  	params.require(:feature).permit(
            :id,
            :name,
            :photo,
            :video,
            :short_description,
            :long_description,
            :active,
            )
  end
end

app/controllers/dashboard/landing_page_settings_controller.rb
class Dashboard::LandingPageSettingsController < Dashboard::ResourceController
  def landing_page_setting_params
  	params.require(:landing_page_setting).permit(
            :id,
            :photo_1,
            :photo_2,
            :photo_3,
            :photo_4,
            :video_1,
            :video_2,
            :video_3,
            :video_4,
            :call_to_action_background,
            :header_message,
            :subheader_message,
            :header_description_message,
            :endorsement_header,
            :endorsement_description,
            :testimonial_header,
            :testimonial_description,
            :features_header,
            :features_description,
            :owners_header,
            :owners_description,
            :contact_messages_header,
            :contact_messages_description,
            :plans_header,
            :plans_description
            )
  end
end

app/controllers/dashboard/owners_controller.rb
class Dashboard::OwnersController < Dashboard::ResourceController
  def owner_params
    params.require(:owner).permit(
            :id,
            :name,
            :photo,
            :video,
            :quote,
            :designation,
            :description,
            :active,
            )
  end
end

app/controllers/dashboard/plans_controller.rb
class Dashboard::PlansController < Dashboard::ResourceController
  def plan_params
    params.require(:plan).permit(
            :id,
            :name,
            :photo,
            :video,
            :price,
            :description,
            :active,
            )
  end
end

app/controllers/dashboard/resource_controller.rb
class Dashboard::ResourceController < Dashboard::ApplicationController
  inherit_resources
  respond_to :html

  has_scope :page, default: 1
  self.responder = Dashboard::Responder
end

app/controllers/dashboard/responder.rb
class Dashboard::Responder < ActionController::Responder

  include Responders::FlashResponder
  include Responders::HttpCacheResponder

  def initialize(*)
    super
    @flash_now = :on_failure
  end

end

app/controllers/dashboard/roles_controller.rb
class Dashboard::RolesController < Dashboard::ResourceController
  def role_params
  params.require(:role).permit(
          :id,
          :name,
          )
  end
end

app/controllers/dashboard/site_settings_controller.rb
class Dashboard::SiteSettingsController < Dashboard::ResourceController

  def create
    site_setting = SiteSetting.new(site_setting_params)
    if site_setting.save
      redirect_to edit_dashboard_site_setting_url(site_setting)
    else
      render action: :new
    end
  end

  def site_setting_params
    params.require(:site_setting).permit(
          :id,
          :site_name,
          :site_description,
          :site_icon,
          :site_logo,
          )
  end
end

app/controllers/dashboard/testimonials_controller.rb
class Dashboard::TestimonialsController < Dashboard::ResourceController
  def testimonial_params
    params.require(:testimonial).permit(
          :id,
          :name,
          :company_name,
          :photo,
          :video,
          :description,
          :active,
          )
  end
end

app/controllers/dashboard/user_home_page_settings_controller.rb
class Dashboard::UserHomePageSettingsController < Dashboard::ResourceController
  def user_home_page_setting_params
    params.require(:user_home_page_setting).permit(
          :id,
          :create_company_photo,
          :connect_company_photo,
          :company_settings_photo,
          )
  end
end

app/helpers/dashboard/application_helper.rb
module Dashboard::ApplicationHelper

  def better_file_size(file_size)
    number_with_delimiter(file_size, delimiter: ',', precision: 2)
  end
end

app/helpers/dashboard/contact_messages_helper.rb
module Dashboard::ContactMessagesHelper
end

app/helpers/dashboard/endorsements_helper.rb
module Dashboard::EndorsementsHelper
end

app/helpers/dashboard/features_helper.rb
module Dashboard::FeaturesHelper
end

app/helpers/dashboard/landing_page_settings_helper.rb
module Dashboard::LandingPageSettingsHelper
end

app/helpers/dashboard/owners_helper.rb
module Dashboard::OwnersHelper
end

app/helpers/dashboard/plans_helper.rb
module Dashboard::PlansHelper
end

app/views/dashboard/partials/_navbar.html.erb
<div data-sticky-container>
  <div class="menu-vertical sticky padding" data-sticky data-margin-top="0" >
    <h1 class="text-center">Tseklis</h1>
    <ul class="vertical menu accordion-menu" data-accordion-menu>
      <li>
      </li>
      <li>
        <a>Features</a>
        <ul class="menu vertical nested">
          <li><%= link_to "Create", new_dashboard_feature_url %></li>
          <li><%= link_to "Index",  dashboard_features_url %></li>
        </ul>
      </li>
      <li>
        <a>Testimonials</a>
        <ul class="menu vertical nested">
          <li><%= link_to "Create", new_dashboard_testimonial_url %></li>
          <li><%= link_to "Index",  dashboard_testimonials_url %></li>
        </ul>
      </li>
      <li>
        <a>Endorsements</a>
        <ul class="menu vertical nested">
          <li><%= link_to "Create", new_dashboard_endorsement_url %></li>
          <li><%= link_to "Index",  dashboard_endorsements_url %></li>
        </ul>
      </li>
      <li>
        <a>Plans</a>
        <ul class="menu vertical nested">
          <li><%= link_to "Create", new_dashboard_plan_url %></li>
          <li><%= link_to "Index",  dashboard_plans_url %></li>
        </ul>
      </li>
      <li>
        <a>Roles</a>
        <ul class="menu vertical nested">
          <li><%= link_to "Create", new_dashboard_role_url %></li>
          <li><%= link_to "Index",  dashboard_roles_url %></li>
        </ul>
      </li>
      <li>
        <a>Company Owners</a>
        <ul class="menu vertical nested">
          <li><%= link_to "Create", new_dashboard_owner_url %></li>
          <li><%= link_to "Index",  dashboard_owners_url %></li>
        </ul>
      </li>
      <li>
        <a>Contact Messages</a>
        <ul class="menu vertical nested">
          <li><%= link_to "Index",  dashboard_contact_messages_url %></li>
        </ul>
      </li>
      <li>
        <a>Site Settings</a>
        <ul class="menu vertical nested">
            <%= link_to "Create", new_dashboard_site_setting_url if SiteSetting.last.nil? %>
          </li>
          <li>
            <%= link_to "Update", edit_dashboard_site_setting_url(SiteSetting.last) if SiteSetting.last.present? %>
          </li>
        </ul>
      </li>
      <li>
        <a>Landing Page Settings</a>
        <ul class="menu vertical nested">
          <li>
            <%= link_to "Create", new_dashboard_landing_page_setting_url if LandingPageSetting.last.nil? %>
          </li>
          <li>
            <%= link_to "Update", edit_dashboard_landing_page_setting_url(LandingPageSetting.last) if LandingPageSetting.last.present? %>
          </li>
        </ul>
      </li>
      <li>
        <a>User Home Page Settings</a>
        <ul class="menu vertical nested">
          <li>
            <%= link_to "Create", new_dashboard_user_home_page_setting_url if UserHomePageSetting.last.nil? %>
          </li>
          <li>
            <%= link_to "Update", edit_dashboard_user_home_page_setting_url(UserHomePageSetting.last) if UserHomePageSetting.last.present? %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>