config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'

  devise_for :admins
  devise_for :users, controllers: { registrations: 'users/registrations', confirmations: 'confirmations' }

  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
	end

  resources :users do

  	resource :profile
  	resources :employments do
      resources :leave_requests do
        resource :rejection_message
      end
      get 'leave_request_by_hr' => 'leave_requests#leave_request_by_hr'
      resources :add_leaves, only: [:new, :create]
    end
  end

  resources :companies do
    resources :leave_types
    resources :holidays
    resources :departments
    resources :costs
    resources :reports, only: [:index] do
      collection do
        get :remaining_leaves
      end
    end
    resources :projects do
      get 'enter_time', on: :collection
      post 'entered_time', on: :collection
      get 'reports', on: :collection
      post 'create_client', on: :collection
    end
    resources :time_requests do
      get 'excel_export', on: :collection
    end
    resources :project_times, only: [:update, :create]
    get 'employees' => 'companies#employees_index'
    get 'leave_requests' => 'companies#leave_requests_index'
    resources :invites
  get 'import_page' => 'companies#import_page'
    get 'employee_import_page' => 'companies#employee_import_page'
    post :import_employees
    post :delete_employees
    post :import_leave_requests
    post :delete_leave_requests
  end

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications/notification_index' => 'notifications#notification_index'
  get 'notifications/read_all', to: 'notifications#read_all'


  namespace :dashboard do
    resources :contact_messages
    resources :endorsements
    resources :features
    resources :owners
    resources :plans
    resources :roles
    resources :testimonials
    resources :site_settings
    resources :landing_page_settings
    resources :user_home_page_settings
    resources :plans
    root to: "site_settings#index"
    devise_for :admins, skip: :registrations
  end

  get 'search' => 'pages#search'
  get 'team' => 'pages#team'
	get 'about' => 'pages#about'
	root 'pages#home'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_up

  def index

  end

  def remaining_leaves
    @r_date = re_params unless params[:re].blank?
    if @r_date.nil?
      @r_date2 = nil
    else
      @r_date2 = @r_date[:date_as_of].to_date
    end
    @remaining = User.joins(:employments).where(employments: {company: @company, end_date: nil})
    unless @r_date2.blank?
      @remaining = User.joins(:employments).where(employments: {company: @company}).where('employments.end_date > ? or employments.end_date is ?', @r_date2, nil)
    end

    respond_to do |format|
      format.html
      format.xlsx {
        @remaining = @remaining
        @r_date2 = @r_date2
      }
    end
  end

  def set_up
    @company = Company.find(params[:company_id])
  end

  protected

	def re_params
		params.require(:re).permit(:date_as_of)
	end

end

app/views/reports/index.html.erb
<div class="small-nav white-border-bottom">
	<div class="row small-nav">
		<div class="columns">
			<%= link_to 'Back', url_for(:back), class:  'small-nav-link' %> 	&nbsp; 	&nbsp; | 	&nbsp; &nbsp;  <%= link_to "Home", root_url, class: 'small-nav-link' %> &nbsp; > &nbsp; <%= link_to @company.name, company_url(@company), class: 'small-nav-link' %>  &nbsp; >  &nbsp; Reports
		</div>
	</div>
</div>
<div class="space2"></div>
<div class="row text-center">
  <div class="column">
    <h2>Reports</h2>
    <h5>
      <%= link_to "Remaining Leaves", remaining_leaves_company_reports_url(@company)%>
    </h5>
  </div>
</div>

app/views/reports/remaining_leaves.html.erb
<div class="small-nav white-border-bottom">
	<div class="row small-nav">
		<div class="columns">
			<%= link_to 'Back', url_for(:back), class:  'small-nav-link' %> 	&nbsp; 	&nbsp; | 	&nbsp; &nbsp;  <%= link_to "Home", root_url, class: 'small-nav-link' %> &nbsp; > &nbsp; <%= link_to @company.name, company_url(@company), class: 'small-nav-link' %>  &nbsp; > &nbsp; <%= link_to "Reports", company_reports_url(@company), class: 'small-nav-link' %> &nbsp; > &nbsp; Remaining Leaves
		</div>
	</div>
</div>
<div class="space2"></div>
<div class="row">
  <div class="columns medium-6">
    <h4>Remaining Leaves <small><%= 'as of ' + better_date(@r_date2) unless @r_date.blank? %></small></h4>
  </div>
  <div class="columns medium-6 text-right">
    <%= link_to "Export to .xlsx", remaining_leaves_company_reports_url(@company, format: 'xlsx', re: @r_date), class: 'button primary' %>
    <%= render 'reports/remaining_leaves/remaining_date' %>
  </div>
</div>
<div class="row">
  <div class="columns">
    <%= render 'reports/remaining_leaves/remaining_leaves_table' %>
  </div>
</div>